### ISSUE TITLE
System DLL included when build

### ISSUE THREAD

**Issue by tuanbui918** [c0shea/IdParser#27]
Hi, I installed the package via Nuget. When I build my project, the build folder now include a lot of the system DLLs. Is there anyway to avoid this?

**Comment by c0shea** [comment]
No. This is a .NET Standard package, so if your project is using .NET Framework for example, it will pull in all of the necessary system dependencies. This isn't a problem and is how .NET Standard was designed; to be xcopy deployable without relying on system dlls that may or may not be GAC'd.

**Comment by c0shea** [comment]
See [this](https://stackoverflow.com/questions/44974931/more-than-96-assemblies-of-net-standard-2-are-copied-to-the-bin-folder-of-conso) for more info.
